# Generated by Django 3.2.7 on 2021-10-31 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('user_firstname', models.CharField(max_length=50)),
                ('user_lastname', models.CharField(max_length=50)),
                ('user_phone_number', models.CharField(max_length=13, null=True)),
                ('user_lang', models.CharField(choices=[('ru', 'Рус'), ('kz', 'Қаз')], default='ru', max_length=2)),
                ('user_school_name', models.CharField(max_length=100, null=True)),
                ('user_grade', models.IntegerField(null=True)),
                ('user_location', models.CharField(max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=30)),
                ('course_description', models.CharField(max_length=300)),
                ('course_avatar', models.CharField(default='/static/img/course_avatar/math-avatar.png', max_length=300)),
                ('course_thumbnail', models.CharField(default='/static/img/course_thumbnail/math-card.jpg', max_length=300)),
                ('course_supervisor', models.CharField(max_length=100)),
                ('course_supervisor_avatar', models.CharField(default='https://cdn0.iconfinder.com/data/icons/user-pictures/100/male-512.png', max_length=300)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('step_id', models.AutoField(primary_key=True, serialize=False)),
                ('step_name', models.CharField(blank=True, max_length=100)),
                ('step_order', models.PositiveSmallIntegerField(default=0)),
                ('step_type', models.PositiveSmallIntegerField(choices=[(0, 'HTML'), (1, 'Test')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('theme_id', models.AutoField(primary_key=True, serialize=False)),
                ('theme_name', models.CharField(max_length=30)),
                ('theme_order', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='HTML',
            fields=[
                ('content', models.TextField()),
                ('step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.step')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=100)),
                ('unit_description', models.CharField(max_length=100)),
                ('unit_order', models.IntegerField(default=0)),
                ('author_name', models.CharField(max_length=100, null=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.theme')),
            ],
            options={
                'unique_together': {('theme', 'unit_order')},
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_json', models.TextField(blank=True, default='')),
                ('test_difficulty', models.PositiveSmallIntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=1)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.step')),
            ],
        ),
        migrations.AddField(
            model_name='step',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.unit'),
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qg_text', models.TextField(blank=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.test')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('a1', models.CharField(help_text='This must be correct answer', max_length=100)),
                ('a2', models.CharField(max_length=100)),
                ('a3', models.CharField(max_length=100)),
                ('a4', models.CharField(max_length=100)),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.questiongroup')),
            ],
        ),
        migrations.CreateModel(
            name='CourseAttd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_steps', models.TextField(blank=True)),
                ('stop_on', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompletedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cq_correct', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together={('unit', 'step_order')},
        ),
    ]
